FROM openjdk:8

RUN apk --update add \
    ca-certificates \
    bash \
    curl \
    build-base \
    gcc \
    python \
    python-dev \
    py-pip

ADD . /project
WORKDIR /project

ENTRYPOINT ["/bin/bash"]
